use_frameworks!

target 'YXLCustomAlertView_Example' do
  pod 'YXLCustomAlertView', :path => '../'

  target 'YXLCustomAlertView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
